# Generated by Django 4.0.5 on 2022-07-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('react_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
